server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zoo_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root            #(education purpose)
    password: Root1234!       #(education purpose)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update    # tablo/kolonları otomatik oluştur-güncelle
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always        # data.sql varsa çalışsın

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

# JWT (education purpose)
app:
  jwt:
    secret: super_secret_please_change_later
    expiration-ms: 3600000

# CORS (education purpose)
cors:
  allowed-origins: "http://localhost:4200,http://localhost:5173,*"

ratelimit:
  animals:
    capacity: 60      # dakikalık kova kapasitesi
    refill: 60        # dakikada eklenecek token